name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        deno_version:
          - lts
          - latest
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Verify formatting
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        # https://github.com/denoland/deno/issues/30831
        if: matrix.os != 'ubuntu-latest' && matrix.deno_version != 'lts'
        run: deno task test

      - name: Test upgrade
        run: deno run -A cli.ts upgrade
